### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by y-spreen** [moxer-theme/code-theme-generator#2]
Python lacks a lot of essential highlighting features, i.e. `self` is not highlighted.

See also: https://github.com/material-theme/vsc-material-theme/issues/427

**Comment by equinusocio** [comment]
Please provide scopes that use different colors.

**Comment by y-spreen** [comment]
Can you clarify?

**Comment by y-spreen** [comment]
```
"variable.parameter.function.language.special",
"variable.parameter"
```

**Comment by equinusocio** [comment]
We need also code a valid code snippet and the name (if used) of the language extension.

**Comment by equinusocio** [comment]
Working on it, can you send a big and valid python code snippet?

**Comment by equinusocio** [comment]
Python highlight has been improved with the new release. Please check.

**Comment by y-spreen** [comment]
![image](https://user-images.githubusercontent.com/12631527/72174720-5e6dd500-33a8-11ea-9ac6-0e7c062260be.png)
For some reason it's sometimes highlighted (clean_job(self)) but sometimes white (self.is_node)

**Comment by y-spreen** [comment]
My current theme for comparison
![image](https://user-images.githubusercontent.com/12631527/72174910-d2a87880-33a8-11ea-999a-13bb41b0e728.png)

**Comment by y-spreen** [comment]
Code from https://github.com/bromberglab/webservice-server/blob/master/django/app/models/job.py#L500

**Comment by equinusocio** [comment]
That's correct. Closing this.

**Comment by y-spreen** [comment]
How's that correct? It's very inconsistent and makes the code very hard to read

**Comment by equinusocio** [comment]
`self` is a variable, our variable are white/foreground. The `self` inside a function is a variable parameter (and it has a paleblue highlight)

**Comment by y-spreen** [comment]
It's not really just a variable. It's a special keyword.

This is what I expect: (regardless of the colors, just talking about the distinction)
![image](https://user-images.githubusercontent.com/12631527/72180764-d55d9a80-33b5-11ea-9c5a-64901e9b8398.png)

And this is what it looks like:
![image](https://user-images.githubusercontent.com/12631527/72180781-dee70280-33b5-11ea-9abf-b6922711a626.png)

The issue is not resolved.

**Comment by y-spreen** [comment]
Parameters are also inconsistent since self behaves differently as a parameter but not outside of a function call.
![image](https://user-images.githubusercontent.com/12631527/72180934-4735e400-33b6-11ea-822c-e048a9e0a08a.png)

**Comment by equinusocio** [comment]
That's depends by the assigned scope, if it's white, it has a variable scope assigned. We don't control that.

**Comment by y-spreen** [comment]
Apparently it is possible to highlight this correctly, other themes do it, the old material theme did that. I think it's more important what it looks like, not what the technicalities of the scopes are.

Self should be highlighted and not white

**Comment by equinusocio** [comment]
Self is currently highlighted correctly as any other variable in other languages. We prefer consistency and maintainability over personal taste. Anyway, thank you for feedback.
