### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by yspreen** [moxer-theme/code-theme-generator#3]
Ruby lacks a lot of essential highlighting/separation, i.e.

![image](https://user-images.githubusercontent.com/12631527/72022231-e97e8c00-323d-11ea-9f2a-a06e6adcc7e4.png)
vs
![image](https://user-images.githubusercontent.com/12631527/72022243-f00d0380-323d-11ea-8533-24b04f97ea5b.png)

See also https://github.com/material-theme/vsc-material-theme/issues/424

**Comment by equinusocio** [comment]
Please provide scopes that use different colors.

**Comment by equinusocio** [comment]
Closing due to missing and vague informations.
