### ISSUE TITLE
Python self consistency

### ISSUE THREAD

**Issue by y-spreen** [moxer-theme/code-theme-generator#8]
These two screenshots are taken from the current theme:
![image](https://user-images.githubusercontent.com/12631527/72198548-e8478d80-33fc-11ea-91e3-e7c739d5a2f1.png)
![image](https://user-images.githubusercontent.com/12631527/72198551-eda4d800-33fc-11ea-8d28-15d028e0675d.png)

Apparently self is not highlighted. Neither are parameters in a function call. But self inside a function is highlighted.

I think consistency is important so I wanted to open this issue.

**Comment by equinusocio** [comment]
Again, `self` is highlighted as any other variable in other language, is white (foreground color). We made a small fix to keep the self white even inside function call and as parameter, it will be released next release, probably next month or later.
